# Generated by Django 4.1.3 on 2024-09-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweatapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sweatapi.type'),
        ),
        migrations.AlterUniqueTogether(
            name='workouttype',
            unique_together={('workout', 'type_id')},
        ),
    ]
