# Generated by Django 4.1.3 on 2024-09-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweatapi', '0005_remove_workout_type_workout_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='sweatapi.workouttype'),
        ),
    ]
