# Generated by Django 4.1.3 on 2024-09-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweatapi', '0006_alter_workout_workout_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workouttype',
            unique_together={('workout', 'type_id', 'type')},
        ),
    ]
