# Generated by Django 4.1.3 on 2024-09-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweatapi', '0007_alter_workouttype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workouttype',
            unique_together={('workout', 'type_id')},
        ),
        migrations.RemoveField(
            model_name='workouttype',
            name='type',
        ),
    ]
