# Generated by Django 4.1.3 on 2024-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatapi', '0008_alter_workouttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workouttype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workouttype',
            name='type',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workouttype',
            unique_together={('workout', 'type_id', 'type')},
        ),
    ]
